-- ============================================================================
--  عروض الأسعار: جدول الملفات المرفقة + مخزن الملفات السحابي
--  Quotation attachments: metadata table + cloud storage bucket
--
--  شغّل هذا الملف مرة واحدة في: Supabase Dashboard > SQL Editor > New query
--  Run once in: Supabase Dashboard > SQL Editor > New query
--  السكربت آمن ويمكن تشغيله أكثر من مرة / safe to run more than once.
-- ============================================================================

-- 1) جدول بيانات الملفات المرفقة -------------------------------------------
create table if not exists public.quotation_files (
  id bigint generated by default as identity primary key,
  quotation_id bigint not null references public.quotations(id) on delete cascade,
  file_name text not null,
  file_type text,
  file_size bigint,
  storage_path text not null,
  public_url text,
  extracted_text text,
  uploaded_at timestamptz not null default now()
);

create index if not exists quotation_files_quotation_id_idx
  on public.quotation_files (quotation_id);

alter table public.quotation_files enable row level security;

drop policy if exists "Enable read access for all users" on public.quotation_files;
drop policy if exists "Enable insert access for all users" on public.quotation_files;
drop policy if exists "Enable update access for all users" on public.quotation_files;
drop policy if exists "Enable delete access for all users" on public.quotation_files;

create policy "Enable read access for all users"
  on public.quotation_files for select using (true);
create policy "Enable insert access for all users"
  on public.quotation_files for insert with check (true);
create policy "Enable update access for all users"
  on public.quotation_files for update using (true);
create policy "Enable delete access for all users"
  on public.quotation_files for delete using (true);

-- 2) مخزن الملفات (Storage bucket) ------------------------------------------
-- عام للقراءة حتى يمكن فتح الملف وطباعته مباشرة من الرابط.
-- Public read so the file can be opened and printed straight from its URL.
insert into storage.buckets (id, name, public, file_size_limit)
values ('quotation-files', 'quotation-files', true, 26214400)  -- 25 MB
on conflict (id) do update
  set public = true,
      file_size_limit = 26214400;

-- 3) صلاحيات المخزن ---------------------------------------------------------
drop policy if exists "quotation files public read"   on storage.objects;
drop policy if exists "quotation files public insert" on storage.objects;
drop policy if exists "quotation files public update" on storage.objects;
drop policy if exists "quotation files public delete" on storage.objects;

create policy "quotation files public read"
  on storage.objects for select
  using (bucket_id = 'quotation-files');

create policy "quotation files public insert"
  on storage.objects for insert
  with check (bucket_id = 'quotation-files');

create policy "quotation files public update"
  on storage.objects for update
  using (bucket_id = 'quotation-files');

create policy "quotation files public delete"
  on storage.objects for delete
  using (bucket_id = 'quotation-files');

-- ملاحظة أمنية / Security note:
-- هذه الصلاحيات مفتوحة للجميع مثل باقي جداول النظام الحالية.
-- عند تفعيل مصادقة Supabase، استبدل true و using(...) بشروط مثل:
--   using (auth.uid() is not null)
