-- Safe repair script for quotations data sync.
-- Run this once if your public.quotations table was created before the
-- Quotation No. / Invoice No. / Project No. fields were added.
-- This script is safe to run multiple times.

create table if not exists public.quotations (
  id bigint generated by default as identity primary key,
  date date,
  visit_time text,
  company_name text not null,
  company_scope text,
  contact_person text,
  mobile text,
  email text,
  amount numeric(14,2),
  quotation_no text,
  invoice_no text,
  project_no text,
  subject text,
  next_followup date,
  status text not null default 'open' check (status in ('open','submitted','followup','paymentPending','closed')),
  requirement text,
  followup_action text,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.quotations_activity (
  id bigint generated by default as identity primary key,
  quotation_id bigint not null references public.quotations(id) on delete cascade,
  log_date date not null default current_date,
  status text,
  note text,
  created_at timestamptz not null default now()
);

alter table public.quotations add column if not exists quotation_no text;
alter table public.quotations add column if not exists invoice_no text;
alter table public.quotations add column if not exists project_no text;

alter table public.quotations enable row level security;
alter table public.quotations_activity enable row level security;

drop policy if exists "Enable read access for all users" on public.quotations;
drop policy if exists "Enable insert access for all users" on public.quotations;
drop policy if exists "Enable update access for all users" on public.quotations;
drop policy if exists "Enable delete access for all users" on public.quotations;

drop policy if exists "Enable read access for all users" on public.quotations_activity;
drop policy if exists "Enable insert access for all users" on public.quotations_activity;
drop policy if exists "Enable update access for all users" on public.quotations_activity;
drop policy if exists "Enable delete access for all users" on public.quotations_activity;

create policy "Enable read access for all users" on public.quotations for select using (true);
create policy "Enable insert access for all users" on public.quotations for insert with check (true);
create policy "Enable update access for all users" on public.quotations for update using (true);
create policy "Enable delete access for all users" on public.quotations for delete using (true);

create policy "Enable read access for all users" on public.quotations_activity for select using (true);
create policy "Enable insert access for all users" on public.quotations_activity for insert with check (true);
create policy "Enable update access for all users" on public.quotations_activity for update using (true);
create policy "Enable delete access for all users" on public.quotations_activity for delete using (true);
