-- Optional Supabase schema for moving data from browser storage to a shared database.
create table if not exists public.debtors (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null default 'individual' check (type in ('individual', 'company')),
  company_number text,
  cr_number text,
  phone text,
  total numeric(14,2) not null default 0,
  paid numeric(14,2) not null default 0,
  due date,
  notes text,
  rep_id bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.debtors_activity (
  id bigint generated by default as identity primary key,
  debtor_id bigint not null references public.debtors(id) on delete cascade,
  type text not null check (type in ('payment', 'follow')),
  activity_date date not null default current_date,
  amount numeric(14,2),
  method text,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.reps (
  id bigint primary key,
  name text not null,
  phone text,
  area text,
  created_at timestamptz not null default now()
);
-- RLS Policies for reps table
-- Drop existing policies if they exist
drop policy if exists "Enable read access for all users" on public.reps;
drop policy if exists "Enable insert access for all users" on public.reps;
drop policy if exists "Enable update access for all users" on public.reps;
drop policy if exists "Enable delete access for all users" on public.reps;
-- Allow public read access (for demo purposes - restrict in production)
create policy "Enable read access for all users" on public.reps for select using (true);
-- Allow public insert access (for demo purposes - restrict in production)
create policy "Enable insert access for all users" on public.reps for insert with check (true);
-- Allow public update access (for demo purposes - restrict in production)
create policy "Enable update access for all users" on public.reps for update using (true);
-- Allow public delete access (for demo purposes - restrict in production)
create policy "Enable delete access for all users" on public.reps for delete using (true);

create table if not exists public.app_settings (
  id bigint primary key,
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
-- RLS Policies for app_settings table
-- Drop existing policies if they exist
drop policy if exists "Enable read access for all users" on public.app_settings;
drop policy if exists "Enable insert access for all users" on public.app_settings;
drop policy if exists "Enable update access for all users" on public.app_settings;
drop policy if exists "Enable delete access for all users" on public.app_settings;
-- Allow public read access (for demo purposes - restrict in production)
create policy "Enable read access for all users" on public.app_settings for select using (true);
-- Allow public insert access (for demo purposes - restrict in production)
create policy "Enable insert access for all users" on public.app_settings for insert with check (true);
-- Allow public update access (for demo purposes - restrict in production)
create policy "Enable update access for all users" on public.app_settings for update using (true);
-- Allow public delete access (for demo purposes - restrict in production)
create policy "Enable delete access for all users" on public.app_settings for delete using (true);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  role text not null default 'viewer' check (role in ('admin', 'collector', 'viewer')),
  rep_id bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  date timestamptz not null default now(),
  "user" text not null,
  action text not null,
  details text,
  created_at timestamptz not null default now()
);

alter table public.debtors enable row level security;
alter table public.debtors_activity enable row level security;
alter table public.reps enable row level security;
alter table public.app_settings enable row level security;
alter table public.users enable row level security;
alter table public.audit_log enable row level security;

-- RLS Policies for debtors table
-- Drop existing policies if they exist
drop policy if exists "Enable read access for all users" on public.debtors;
drop policy if exists "Enable insert access for all users" on public.debtors;
drop policy if exists "Enable update access for all users" on public.debtors;
drop policy if exists "Enable delete access for all users" on public.debtors;
-- Allow public read access (for demo purposes - restrict in production)
create policy "Enable read access for all users" on public.debtors for select using (true);
-- Allow public insert access (for demo purposes - restrict in production)
create policy "Enable insert access for all users" on public.debtors for insert with check (true);
-- Allow public update access (for demo purposes - restrict in production)
create policy "Enable update access for all users" on public.debtors for update using (true);
-- Allow public delete access (for demo purposes - restrict in production)
create policy "Enable delete access for all users" on public.debtors for delete using (true);

-- RLS Policies for debtors_activity table
-- Drop existing policies if they exist
drop policy if exists "Enable read access for all users" on public.debtors_activity;
drop policy if exists "Enable insert access for all users" on public.debtors_activity;
drop policy if exists "Enable update access for all users" on public.debtors_activity;
drop policy if exists "Enable delete access for all users" on public.debtors_activity;
-- Allow public read access (for demo purposes - restrict in production)
create policy "Enable read access for all users" on public.debtors_activity for select using (true);
-- Allow public insert access (for demo purposes - restrict in production)
create policy "Enable insert access for all users" on public.debtors_activity for insert with check (true);
-- Allow public update access (for demo purposes - restrict in production)
create policy "Enable update access for all users" on public.debtors_activity for update using (true);
-- Allow public delete access (for demo purposes - restrict in production)
create policy "Enable delete access for all users" on public.debtors_activity for delete using (true);

-- RLS Policies for users table
-- Drop existing policies if they exist
drop policy if exists "Enable read access for all users" on public.users;
drop policy if exists "Enable insert access for all users" on public.users;
drop policy if exists "Enable update access for all users" on public.users;
drop policy if exists "Enable delete access for all users" on public.users;
-- Allow public read access (for demo purposes - restrict in production)
create policy "Enable read access for all users" on public.users for select using (true);
-- Allow public insert access (for demo purposes - restrict in production)
create policy "Enable insert access for all users" on public.users for insert with check (true);
-- Allow public update access (for demo purposes - restrict in production)
create policy "Enable update access for all users" on public.users for update using (true);
-- Allow public delete access (for demo purposes - restrict in production)
create policy "Enable delete access for all users" on public.users for delete using (true);

-- RLS Policies for audit_log table
-- Drop existing policies if they exist
drop policy if exists "Enable read access for all users" on public.audit_log;
drop policy if exists "Enable insert access for all users" on public.audit_log;
drop policy if exists "Enable update access for all users" on public.audit_log;
drop policy if exists "Enable delete access for all users" on public.audit_log;
-- Allow public read access (for demo purposes - restrict in production)
create policy "Enable read access for all users" on public.audit_log for select using (true);
-- Allow public insert access (for demo purposes - restrict in production)
create policy "Enable insert access for all users" on public.audit_log for insert with check (true);
-- Allow public update access (for demo purposes - restrict in production)
create policy "Enable update access for all users" on public.audit_log for update using (true);
-- Allow public delete access (for demo purposes - restrict in production)
create policy "Enable delete access for all users" on public.audit_log for delete using (true);

-- Note: For production, replace 'true' with proper authentication checks:
-- Example: using (auth.uid() is not null) or more specific role-based policies

-- ============== QUOTATIONS (عروض الأسعار) ==============
create table if not exists public.quotations (
  id bigint generated by default as identity primary key,
  date date,
  visit_time text,
  company_name text not null,
  company_scope text,
  contact_person text,
  mobile text,
  email text,
  amount numeric(14,2),
  quotation_no text,
  invoice_no text,
  project_no text,
  subject text,
  next_followup date,
  status text not null default 'open' check (status in ('open','submitted','followup','paymentPending','closed')),
  requirement text,
  followup_action text,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.quotations_activity (
  id bigint generated by default as identity primary key,
  quotation_id bigint not null references public.quotations(id) on delete cascade,
  log_date date not null default current_date,
  status text,
  note text,
  created_at timestamptz not null default now()
);

alter table public.quotations enable row level security;
alter table public.quotations_activity enable row level security;

-- RLS Policies for quotations table
drop policy if exists "Enable read access for all users" on public.quotations;
drop policy if exists "Enable insert access for all users" on public.quotations;
drop policy if exists "Enable update access for all users" on public.quotations;
drop policy if exists "Enable delete access for all users" on public.quotations;
create policy "Enable read access for all users" on public.quotations for select using (true);
create policy "Enable insert access for all users" on public.quotations for insert with check (true);
create policy "Enable update access for all users" on public.quotations for update using (true);
create policy "Enable delete access for all users" on public.quotations for delete using (true);

-- RLS Policies for quotations_activity table
drop policy if exists "Enable read access for all users" on public.quotations_activity;
drop policy if exists "Enable insert access for all users" on public.quotations_activity;
drop policy if exists "Enable update access for all users" on public.quotations_activity;
drop policy if exists "Enable delete access for all users" on public.quotations_activity;
create policy "Enable read access for all users" on public.quotations_activity for select using (true);
create policy "Enable insert access for all users" on public.quotations_activity for insert with check (true);
create policy "Enable update access for all users" on public.quotations_activity for update using (true);
create policy "Enable delete access for all users" on public.quotations_activity for delete using (true);

