-- Optional Supabase schema for moving data from browser storage to a shared database.
create table if not exists public.debtors (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null default 'individual' check (type in ('individual', 'company')),
  company_number text,
  cr_number text,
  phone text,
  total numeric(14,2) not null default 0,
  paid numeric(14,2) not null default 0,
  due date,
  notes text,
  rep_id bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.debtors_activity (
  id bigint generated by default as identity primary key,
  debtor_id bigint not null references public.debtors(id) on delete cascade,
  type text not null check (type in ('payment', 'follow')),
  activity_date date not null default current_date,
  amount numeric(14,2),
  method text,
  note text,
  created_at timestamptz not null default now()
);

alter table public.debtors enable row level security;
alter table public.debtors_activity enable row level security;

-- Add policies after enabling Supabase Auth. Do not expose service keys in app.js.
