-- Optional Supabase schema for moving data from browser storage to a shared database.
create table if not exists public.debtors (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null default 'individual' check (type in ('individual', 'company')),
  company_number text,
  cr_number text,
  phone text,
  total numeric(14,2) not null default 0,
  paid numeric(14,2) not null default 0,
  due date,
  notes text,
  rep_id bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.debtors_activity (
  id bigint generated by default as identity primary key,
  debtor_id bigint not null references public.debtors(id) on delete cascade,
  type text not null check (type in ('payment', 'follow')),
  activity_date date not null default current_date,
  amount numeric(14,2),
  method text,
  note text,
  created_at timestamptz not null default now()
);

alter table public.debtors enable row level security;
alter table public.debtors_activity enable row level security;

-- RLS Policies for debtors table
-- Allow public read access (for demo purposes - restrict in production)
create policy "Enable read access for all users" on public.debtors for select using (true);
-- Allow public insert access (for demo purposes - restrict in production)
create policy "Enable insert access for all users" on public.debtors for insert with check (true);
-- Allow public update access (for demo purposes - restrict in production)
create policy "Enable update access for all users" on public.debtors for update using (true);
-- Allow public delete access (for demo purposes - restrict in production)
create policy "Enable delete access for all users" on public.debtors for delete using (true);

-- RLS Policies for debtors_activity table
-- Allow public read access (for demo purposes - restrict in production)
create policy "Enable read access for all users" on public.debtors_activity for select using (true);
-- Allow public insert access (for demo purposes - restrict in production)
create policy "Enable insert access for all users" on public.debtors_activity for insert with check (true);
-- Allow public update access (for demo purposes - restrict in production)
create policy "Enable update access for all users" on public.debtors_activity for update using (true);
-- Allow public delete access (for demo purposes - restrict in production)
create policy "Enable delete access for all users" on public.debtors_activity for delete using (true);

-- Note: For production, replace 'true' with proper authentication checks:
-- Example: using (auth.uid() is not null) or more specific role-based policies
